### ISSUE TITLE
node-sass failing to install on OSX (works on Windows)

### ISSUE THREAD

**Issue by bherila** [yarnpkg/yarn#4035]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Attempting to install node-sass is failing on OSX. The same package.json + lockfile install successfully on Windows.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `git clone https://gist.github.com/1611a7ecd566078f3a6d29708cf9cef9.git 161a`

Cloning into '161a'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.

2. `cd 161a/`
3. run `yarn install` →  observe error

```
yarn install
yarn install v0.28.0-20170725.1339
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "commonmark-react-renderer@4.3.3" has incorrect peer dependency "commonmark@^0.27.0 || ^0.26.0 || ^0.24.0".
warning "redux-connect@5.1.0" has incorrect peer dependency "prop-types@~15.x.x".
warning "calipers-gif@2.0.0" has incorrect peer dependency "calipers@2.x.x".
warning "calipers-jpeg@2.0.0" has incorrect peer dependency "calipers@2.x.x".
warning "calipers-png@2.0.0" has incorrect peer dependency "calipers@2.x.x".
warning "postcss-cssnext@2.11.0" has incorrect peer dependency "caniuse-db@^1.0.30000652".
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
[4/4] 📃  Building fresh packages...
[-/3] ⠐ waiting...
[2/3] ⠐ node-sass: Binary saved to /Users/ben/Documents/projects/mw/www/node_modules/node-sass/vendor/darwi
[-/3] ⠐ waiting...
[-/3] ⠈ waiting...
error /Users/ben/Documents/projects/mw/www/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: /Users/ben/Documents/projects/mw/www/node_modules/node-sass
Output:
module.js:487
    throw err;
    ^

Error: Cannot find module './util/resolveCommand'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ben/Documents/projects/mw/www/node_modules/cross-spawn/lib/parse.js:3:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

4. run `npm install` →  no error

**What is the expected behavior?**

No error - packages are installed successfully.

**Please mention your node.js, yarn and operating system version.**

```
Benjamins-MacBook-Pro:161a ben$ node --version
v8.1.4
Benjamins-MacBook-Pro:161a ben$ yarn --version
0.28.0-20170725.1339
```

**Comment by BYK** [comment]
Can you try this with https://5243-49970642-gh.circle-artifacts.com/0/home/ubuntu/yarn/artifacts/yarn-1.0.2.js and see if it goes away?

**Comment by jpickwell** [comment]
Works fine on 1.3.2. It worked with previous 1.x versions as well.

**Comment by paul-soporan** [comment]
Closing as this seems solved.

**Comment by HassanNdam** [comment]
Hello I solved the issue by installing an old version of node (Node 10) using NVM
