### ISSUE TITLE
unable to install sharp 0.18.4

### ISSUE THREAD

**Issue by oprogramador** [yarnpkg/yarn#5658]
# versions
OS: OS X 10.12.6
Node.js: 8.9.4
yarn: 1.5.1

# What is the current behavior?
I have the following `package.json`:
```json
{
  "name": "foo-package",
  "dependencies": {
    "sharp": "^0.18.4"
  }
}
```
Command `yarn install` fails with:
```
warning package.json: No license field
warning ../package.json: No license field
info No lockfile found.
warning my-project: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠂ sharp
[-/1] ⠂ waiting...
[-/1] ⠂ waiting...
[-/1] ⠂ waiting...
error An unexpected error occurred: "/Users/me/my-project/node_modules/sharp: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/me/my-project/node_modules/sharp
Output:
module.js:540
    throw err;
    ^

Error: Cannot find module '/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
```

It creates `yarn-error.log` file with:
```
Arguments: 
  /Users/me/.nvm/versions/node/v8.9.4/bin/node /Users/me/.nvm/versions/node/v8.9.4/bin/yarn install

PATH: 
  /Users/me/.nvm/versions/node/v8.9.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Yarn version: 
  1.5.1

Node version: 
  8.9.4

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "my-project",
    "dependencies": {
      "sharp": "^0.18.4"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: /Users/me/my-project/node_modules/sharp: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c node-gyp rebuild
  Directory: /Users/me/my-project/node_modules/sharp
  Output:
  module.js:540
      throw err;
      ^
  
  Error: Cannot find module '/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
      at Function.Module._resolveFilename (module.js:538:15)
      at Function.Module._load (module.js:468:25)
      at Function.Module.runMain (module.js:684:10)
      at startup (bootstrap_node.js:187:16)
      at bootstrap_node.js:608:3
      at ProcessTermError.MessageError (/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/yarn/lib/cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Socket.stream.socket.on (internal/child_process.js:346:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:554:12)
```

# What is the expected behavior?
Yarn 1.5.1 (the latest) should successfully install `sharp 0.18.4` package with no errors.

# Notes
## npm
 `npm install` works for the provided `package.json` giving the following output:
```
> sharp@0.18.4 install /Users/me/my-project/node_modules/sharp
> node-gyp rebuild

  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
../src/metadata.cc:142:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      debuglog->Call(1, message);
                ^
../../nan/nan.h:1618:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
../src/metadata.cc:147:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1618:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
2 warnings generated.
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
../src/pipeline.cc:1050:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      debuglog->Call(1, message);
                ^
../../nan/nan.h:1618:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
../src/pipeline.cc:1057:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    queueListener->Call(1, queueLength);
                   ^
../../nan/nan.h:1618:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
../src/pipeline.cc:1061:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(3, argv);
              ^
../../nan/nan.h:1618:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
../src/pipeline.cc:1335:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  queueListener->Call(1, queueLength);
                 ^
../../nan/nan.h:1618:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
4 warnings generated.
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/sharp.node
  TOUCH Release/obj.target/win_copy_dlls.stamp
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN my-project@ No description
npm WARN my-project@ No repository field.
npm WARN my-project@ No license field.

added 37 packages from 62 contributors in 51.944s
```

## yarn 0.19.1
`yarn 0.19.1` works for the provided `package.json` giving the following output:
```
yarn install v0.19.1
info No lockfile found.
warning my-project: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 16.76s.
```

However `yarn 0.19.1` fails for the following `package.json`:
```json
{
  "name": "my-project",
  "dependencies": {
    "easy-ffmpeg": "0.0.14",
    "sharp": "^0.18.4"
  }
}
```
with:
```
yarn install v0.19.1
info No lockfile found.
warning my-project: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/2] ⠁ easy-ffmpeg
[2/2] ⠁ sharp: ok
[-/2] ⠁ waiting...
[-/2] ⠁ waiting...
error /Users/me/my-project/node_modules/easy-ffmpeg: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /Users/me/my-project/node_modules/easy-ffmpeg
Output:
/Users/me/my-project/node_modules/tarball-extract/tarball.js:11
    .pipe(tar.Extract({ path: destination}))
              ^

TypeError: tar.Extract is not a function
    at Object.extractTarball (/Users/me/my-project/node_modules/tarball-extract/tarball.js:11:15)
    at WriteStream.<anonymous> (/Users/me/my-project/node_modules/easy-ffmpeg/install.js:25:15)
    at emitNone (events.js:106:13)
    at WriteStream.emit (events.js:208:7)
    at fs.close (fs.js:2078:12)
    at FSReqWrap.oncomplete (fs.js:135:15)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
It creates no `yarn-error.log` file.

**Comment by oprogramador** [comment]
It can related to https://github.com/yarnpkg/yarn/issues/1693

**Comment by rally25rs** [comment]
you might want to try reinstalling node-gyp too. `yarn global add node-gyp`

**Comment by piotr-s-brainhub** [comment]
@rally25rs 
`yarn global add node-gyp` worked after this `yarn install` in this project is still not working.

**Comment by skalfyfan** [comment]
I can confirm this happening for me as well right now!

a) Installed _yarn_ via homebrew `brew install yarn` (v1.6.0)
b) Got the error the first time and decided to globally install `node_gyp) `npm install -g node-gyp`
c) npm install works (but I do not have a package.lock)
d) `yarn install` still **FAILS** with the following:

```
[1/4] ⢀ @newrelic/native-metrics: > node-gyp clean configure
[-/4] ⢀ waiting...
[3/4] ⢀ fsevents
[4/4] ⢀ sonarqube-scanner-node
error /Users/skalfyfan/dev/me/api-v1/node_modules/@newrelic/native-metrics: Command failed.
Exit code: 1
Command: node ./lib/pre-build.js --no-download install native_metrics
Arguments:
Directory: /Users/skalfyfan/dev/me/api-v1/node_modules/@newrelic/native-metrics
Output:
> node-gyp clean configure
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/skalfyfan/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

It looks to me like _yarn_ is looking for `node-gyp` in the incorrect location?

_yarn_ is looking for _node_gyp_ here:
`/Users/skalfyfan/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js`

When it's actually installed here:
 `/Users/skalfyfan/.nvm/versions/node/v8.11.1/lib/node_modules/node-gyp/bin`

**Comment by sth** [comment]
I can reproduce and explain the `easy-ffmpeg` issue you mention:

`easy-ffmpeg` contains the dependency `"tarball-extract": "0.0.3"`. Yarn installs that package version. `tarball-extract@0.0.3` has a dependency `"tar": "*"`. Yarn installs the current `tar` package (version 4.4.1).

But `tarball-extract@0.0.3` doesn't actually work with `tar@4.4.1` and fails when the post-install script of `easy-ffmpeg` tries to use it. `tarball-extract` doesn't declare the correct dependencies. This dependency problem would be fixed in the current version `tarball-extract@0.0.6, but `easy-ffmpeg` explicitly depends on the old version 0.0.3.

The proper solution would be to update `easy-ffmpeg` to use the fixed `tarball-extract@0.0.6`.

**Comment by acchou** [comment]
I have the same problem when compiling `memwatch-next`.

One thing I discovered after playing around a bit: `yarn install` succeeds with npm v5.6.0 but fails with v5.8.0. Can anyone confirm this with other packages?

**Comment by oprogramador** [comment]
@acchou 
you're right installing `sharp` works after switching to `npm 5.6`, however still I have an issue with `easy-ffmpeg`

## npm 5.6, yarn 1.6, only `"sharp": "^0.18.4"` - success
```
⟩ node --version
v8.11.1
⟩ npm --version
5.6.0
⟩ yarn --version
1.6.0
>
⟩ cat package.json
{
  "name": "my-project",
  "dependencies": {
    "sharp": "^0.18.4"
  }
}
⟩ yarn install
yarn install v1.6.0
warning package.json: No license field
info No lockfile found.
warning foo-package: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 15.26s.
```

## npm 5.8, yarn 1.6, only `"sharp": "^0.18.4"` - fail
```
⟩ node --version
v8.11.1
⟩ npm --version
5.8.0
⟩ yarn --version
1.6.0
⟩ cat package.json
{
  "name": "my-project",
  "dependencies": {
    "sharp": "^0.18.4"
  }
}
⟩ yarn install
yarn install v1.6.0
warning package.json: No license field
warning ../../../package.json: No license field
info No lockfile found.
warning foo-package: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠂ sharp
[-/1] ⠂ waiting...
[-/1] ⠂ waiting...
[-/1] ⠂ waiting...
error /Users/me/my-project/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/me/my-project/node_modules/sharp
Output:
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
```

## npm 5.6, yarn 1.6, both `"sharp": "^0.18.4"` and `"easy-ffmpeg": "0.0.14"` - fail
```
⟩ node --version
v8.11.1
⟩ npm --version
5.6.0
⟩ yarn --version
1.6.0
⟩ cat package.json
{
  "name": "my-project",
  "dependencies": {
    "easy-ffmpeg": "0.0.14",
    "sharp": "^0.18.4"
  }
}
⟩ yarn install
yarn install v1.6.0
warning package.json: No license field
warning ../../../package.json: No license field
info No lockfile found.
warning my-project: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/2] ⠐ easy-ffmpeg:     at FSReqWrap.oncomplete (fs.js:135:15)
[2/2] ⠐ sharp:   ^
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
error /Users/me/my-project/node_modules/easy-ffmpeg: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/me/my-project/node_modules/easy-ffmpeg
Output:
/Users/me/my-project/node_modules/tarball-extract/tarball.js:11
    .pipe(tar.Extract({ path: destination}))
              ^

TypeError: tar.Extract is not a function
    at Object.extractTarball (/Users/me/my-project/node_modules/tarball-extract/tarball.js:11:15)
    at WriteStream.<anonymous> (/Users/me/my-project/node_modules/easy-ffmpeg/install.js:25:15)
    at emitNone (events.js:106:13)
```

## npm 5.6, yarn 1.6, only `"easy-ffmpeg": "0.0.14"` - fail
```
⟩ node --version
v8.11.1
⟩ npm --version
5.6.0
⟩ yarn --version
1.6.0
⟩ cat package.json
{
  "name": "my-project",
  "dependencies": {
    "easy-ffmpeg": "0.0.14"
  }
}⟩ yarn install
yarn install v1.6.0
warning package.json: No license field
warning ../../../package.json: No license field
info No lockfile found.
warning my-project: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠐ easy-ffmpeg
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
error /Users/me/my-project/node_modules/easy-ffmpeg: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/me/my-project/node_modules/easy-ffmpeg
Output:
/Users/me/my-project/node_modules/tarball-extract/tarball.js:11
    .pipe(tar.Extract({ path: destination}))
              ^

TypeError: tar.Extract is not a function
    at Object.extractTarball (/Users/me/my-project/node_modules/tarball-extract/tarball.js:11:15)
    at WriteStream.<anonymous> (/Users/me/my-project/node_modules/easy-ffmpeg/install.js:25:15)
    at emitNone (events.js:106:13)
```

**Comment by oprogramador** [comment]
@sth 
I opened a PR in easy-ffmpeg
https://github.com/konsumer/easy-ffmpeg/pull/8

**Comment by paul-soporan** [comment]
Closing as this looks like an external issue.
