### ISSUE TITLE
Bug: yarn throw "Cannot find module '/home/me/.yarn/releases/yarn-1.22.1.cjs'" on any comand

### ISSUE THREAD

**Issue by KostyaTretyak** [yarnpkg/yarn#8906]
I work on Ubuntu 20.04, I don't know what happened, but yarn stopped working altogether. No matter what command I type, it gives me the same error:

```bash
$ yarn --version
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/home/me/.yarn/releases/yarn-1.22.1.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.12.1
```

As far as I can remember, I install yarn using curl (several years ago):

```bash
curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
```

Now I installed yarn v1.22.19 globally via npm but something went wrong. The above error occurs for any version of Node.js. Even deleting the entire folder in `~/node_modules` doesn't help.

**Comment by KostyaTretyak** [comment]
Sorry, I'm closing this issue because I reinstalled Ubuntu myself, so I won't be able to give feedback.
