### ISSUE TITLE
0.23.4 causes "Cannot find module './request'" error

### ISSUE THREAD

**Issue by EvNaverniouk** [yarnpkg/yarn#3349]
**What is the current behavior?**

After upgrading from yarn 0.23.3 to 0.23.4 I can no longer use yarn due this error:

```
Error: Cannot find module './request'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:144:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

This is reported several times after any `yarn ___` command such as `yarn test`.

This issue was not occurring when using 0.23.3

**If the current behavior is a bug, please provide the steps to reproduce.**

I am using MacOS and starting with `yarn@0.23.3` I ran:

```
brew update
brew upgrade
```

And then ran:

```
yarn test
```

inside my project. This caused the error to appear.

**Comment by EvNaverniouk** [comment]
Appears to be caused when `brew upgrade` upgraded me from node `7.9.0` to `7.10.0` which also broke `npm` installed.

This is not `yarn` related. Closing.
