### PR TITLE
Fixes Node 4 compatibility, closes #3591

### LINKED ISSUE #3591: bundledDeps[rootDep].includes is not a function
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**

`yarn check` fails on node 4 with:

```
error An unexpected error occurred: "bundledDeps[rootDep].includes is not a function".
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ yarn check
```

**What is the expected behavior?**

No error.

**Please mention your node.js, yarn and operating system version.**
node: 4.8.2
yarn: 0.26.0

Offending commit: https://github.com/yarnpkg/yarn/pull/3337/files#diff-d14f7375c6a059d2b2ed31247fe52519R330

https://github.com/yarnpkg/yarn/issues/3138

### PR DESCRIPTION
**Pull request by arcanis**
`.includes` is not supported in Node 4 😢

### CODE REVIEW

**Comment by arcanis** [comment]
cc @BYK, I apparently can't flag you as reviewer

**Comment by arcanis** [comment]
Woops, I missed #3592
