### ISSUE TITLE
workspaces nohoist options simply does not work 

### ISSUE THREAD

**Issue by LukasBombach** [yarnpkg/yarn#5397]
I am running yarn 1.3.2

**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
I am using `workspaces` with `nohoist` and when I run `yarn` in my root directory I get the error

    error An unexpected error occurred: "patterns.map is not a function".

**If the current behavior is a bug, please provide the steps to reproduce.**
Use this `package.json` in your root directory:

```json
{
  "name": "verne",
  "version": "0.0.1",
  "description": "A WYSIWYG library that does not suck",
  "private": true,
  "workspaces": {
    "packages": ["packages/*"],
    "nohoist": ["**/verne", "**/verne-react"]
  }
}
```

**What is the expected behavior?**

It should install all dependencies and not hoist packages

**Please mention your node.js, yarn and operating system version.**
Node: v9.6.1
macOS High Sierra 10.13.3

**Comment by LukasBombach** [comment]
ok it's probably related to this https://github.com/yarnpkg/yarn/issues/5089

and I assume i need to upgrade to the release candidate or a nightly build of yarn. I can try that out, but how do I install the release candidate on macOS?

**Comment by rally25rs** [comment]
This command became available in yarn v1.5.0 which I believe you can install with:

```
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.0
```

Note that 1.5.0 is still "pre-release" so you might encounter some other undiscovered bugs as well.

I'll close this issue for now, but if you find that it is still not working on 1.5.0 we can reopen it.

**Comment by LukasBombach** [comment]
Thank You!
