### ISSUE TITLE
error installing phantomjs-prebuilt, with 1.0.x, --ignore-optional, and 2 other deps

### ISSUE THREAD

**Issue by billyvg** [yarnpkg/yarn#4445]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Example error (it doesn't always fail on this module)

```
error /Users/billy/Dev/phantomjs-prebuilt/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/billy/Dev/phantomjs-prebuilt/node_modules/phantomjs-prebuilt
Output:
module.js:491
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/billy/Dev/phantomjs-prebuilt/node_modules/readable-stream/lib/_stream_readable.js:26:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/billyvg/yarn-phantomjs-repro

Above repo will fail to install with
`yarn install --ignore-optional`

**What is the expected behavior?**
To install.  Note this works in `0.27.5_1`

**Please mention your node.js, yarn and operating system version.**
node 8.4.0
yarn 1.0.2
OSX 10.12.6

**Comment by BYK** [comment]
I can reproduce this issue with the provided repo and instructions. Thanks a lot for that!

That said I do not know yet whether this is a bug with yarn or with the packages. I'll investigate.

**Comment by BYK** [comment]
Okay found the culprit: https://github.com/yarnpkg/yarn/pull/3976/files#diff-7066979f95168f7bb59e4f9cfb3ba8fcR211

Fix coming.
