### ISSUE TITLE
yarn throws Error: Cannot find module 'user-home' after upgrade to 0.17.9 from 0.15.1

### ISSUE THREAD

**Issue by gtwilliams03** [yarnpkg/yarn#2076]
yarn 0.17.9; node 6.9.1

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn throws error regarding user-home after upgrading to latest version from 0.15.1

```
MacBook-Pro:severedlinks-app gtw$ yarn
module.js:471
    throw err;
    ^

Error: Cannot find module 'user-home'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gtw/.yarn/lib-legacy/constants.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
MacBook-Pro:severedlinks-app gtw$ yarn
module.js:471
    throw err;
    ^

Error: Cannot find module 'user-home'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gtw/.yarn/lib-legacy/constants.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`npm install -g yarn`

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
node 6.9.1, yarn 0.17.9, macOS Sierra

**Comment by gtwilliams03** [comment]
Tried to globally and locally reinstall user-home module - but it still throws the error.

**Comment by gtwilliams03** [comment]
Removed ~/.yarn directory.  Reinstalled via the `curl -o- -L https://yarnpkg.com/install.sh | bash` script.  Problem went away.
