### ISSUE TITLE
bundledDeps[rootDep].includes is not a function

### ISSUE THREAD

**Issue by CrabDude** [yarnpkg/yarn#3591]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**

`yarn check` fails on node 4 with:

```
error An unexpected error occurred: "bundledDeps[rootDep].includes is not a function".
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ yarn check
```

**What is the expected behavior?**

No error.

**Please mention your node.js, yarn and operating system version.**
node: 4.8.2
yarn: 0.26.0

Offending commit: https://github.com/yarnpkg/yarn/pull/3337/files#diff-d14f7375c6a059d2b2ed31247fe52519R330

https://github.com/yarnpkg/yarn/issues/3138
