### ISSUE TITLE
Cannot find module './_baseClone' after upgrade to 1.9.4

### ISSUE THREAD

**Issue by yooouuri** [yarnpkg/yarn#6298]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After upgrading to 1.9.4, react-native start gives me an error

```
yooouuri@Youris-MacBook-Pro  ~/PhpstormProjects/atlacarte/atlacarte-app   upgrade ●  yarn start
yarn run v1.9.4
$ node node_modules/react-native/local-cli/cli.js start
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './_baseClone'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/yooouuri/PhpstormProjects/atlacarte/atlacarte-app/node_modules/lodash/cloneDeep.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I use NPM, no error occurs.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
brew install yarn
```

```
yooouuri@Youris-MacBook-Pro  ~/PhpstormProjects/atlacarte/atlacarte-app   upgrade ●  yarn -v
1.9.4
```

After it, run `react-native start`

**What is the expected behavior?**
The metro builder to start.

**Please mention your node.js, yarn and operating system version.**
v10.9.0
1.9.4
Mac OS 10.13.6

**Comment by yooouuri** [comment]
I removed yarn with brew and installed the RC (1.9.2).

`curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc`

And it is working

```
yooouuri@Youris-MacBook-Pro  ~/PhpstormProjects/atlacarte/atlacarte-app   upgrade ●  yarn start
yarn run v1.9.2
$ node node_modules/react-native/local-cli/cli.js start
Scanning folders for symlinks in /Users/yooouuri/PhpstormProjects/atlacarte/atlacarte-app/node_modules (14ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/yooouuri/PhpstormProjects/atlacarte/atlacarte-app


Metro Bundler ready.

Loading dependency graph, done.
```

**Comment by dead** [comment]
I'm having the same issue in Windows 10 and react-create-app. In both 1.9.4 and 1.10.0.
Downgrading to 1.9.2 fixed the problem.
